name: RFTD
main: fr.kyriog.rftd.RftdPlugin
version: 0.3.0
commands:
  team:
    usage: "Usage: /team <add|join>"
    description: Easily manage teams for RFTD
  egg:
    description: Defines dragon egg deposit block
  start:
    description: Starts RFTD season
