name: RFTD
main: fr.kyriog.rftd.RftdPlugin
version: 0.3.0-SNAPSHOT
commands:
  team:
    usage: "Usage: /team <add|join>"
    description: Easily manage teams for RFTD
  egg:
    description: Defines dragon egg deposit block
  spawnpoint:
    description: Set players spawn point
  start:
    description: Starts RFTD season
